### ISSUE TITLE
Include object boundaries in hashing

### ISSUE THREAD

**Issue by fweimer** [cgwalters/git-evtag#4]
Based on the pseudo-code, the tree traversal hashes the sub-objects without any length indicator or explicit delimiter. Instead, it relies on the object lengths encoded at the Git layer. I think this kind of layering violation is problematic. You should encode these boundaries at your hashing layer.

Otherwise, you could just sign the top-level commit because you are not isolated from SHA-1 hashing issues Git may be troubled with one day.

**Comment by cgwalters** [comment]
I'm using https://tools.ietf.org/html/rfc4270 and https://en.wikipedia.org/wiki/Hash_function_security_summary among others as a reference here.  In RFC4270 terms, I think git-evtag is "Integrity protection", for which a collision attack is not enough.

The target hash is covered by the GPG signature (and leaving aside attacks on the signature). Therefore we need a second preimage.  And general consensus seems to be the SHA-2 family is still strong against those attacks.

What I'm trying to understand here is - because git-evtag is compuing `SHA512(a || b || c || d ...)`, does the independence of the individual components make it any easier to attack the hash?  If I am able to find a `X != b` where `SHA512(a || b || c ...) = SHA512(a || X || c ...) `, it's certainly true that git-evtag still considers the message valid.

But that goes back to the point that what we're hashing actually looks like:

`SHA512(commit 112 <112 bytes> || tree 89 <89 bytes> || blob 42 <42 bytes> || blob 78 <78 bytes> ...)`.

The fact that git objects do have the length encoded seems to me (again, I am not a cryptographer) to make it harder to mount attacks like the "Meet in the middle" technique referenced in http://link.springer.com/chapter/10.1007%2F978-3-642-10366-7_34 because the size has to match the expected version.

What you seem to be suggesting is to make the hash something like:

SHA512("object 112" || a || "object 89" || b || "object 42" || c ...)` in addition to the object type header and length that git already has.

But how is it a layering violation if I *know* I am hashing git objects in a known format (and that format *cannot* change)?

That said...I'm not opposed to it.  I just want to better understand the potential attacks.

**Comment by cgwalters** [comment]
And are there any other uses of cryptographic checksums that do something like what you're talking about?  For example, https://en.wikipedia.org/wiki/X.690#DER_encoding seems analogous here - they only defined a canonicalized format, the checksum algorithm doesn't do anything on *top* of DER (right?)

**Comment by fweimer** [comment]
> But how is it a layering violation if I know I am hashing git objects in a known format (and that format cannot change)?

The knowledge itself is a layering violation. And I can't find any documentation that states this is an inherent property of the Git object format future revisions will keep.

**Comment by cgwalters** [comment]
https://github.com/git/git/blob/master/t/t0000-basic.sh#L15
And that points to:
https://github.com/git/git/commit/d98b46f

Which was made for obvious reasons - gzip output may vary by compression level, version of the encoder, etc.

That was very early in git's history - just two weeks after its initial commit.  Any change *now* would be seriously traumatic for the ecosystem.  Were someone to make any change, git might as well envision other things like switching to sha256 (as OSTree used from the start).

Any switch would mean every client, upon upgrading, would suddenly start having duplicate copies of the objects referenced in new commits...I have trouble picturing the impact.

There's some musings here: https://lwn.net/Articles/370907/
And here: http://yarchive.net/comp/linux/git.html

And http://mikegerwitz.com/papers/git-horror-story is a...large page with a lot of links.

Including to this thread: http://thread.gmane.org/gmane.comp.version-control.git/26106/focus=26112

I think the bottom line here is anything like that was to happen (which seems very unlikely), git-evtag would just be able to learn how to convert "V2" objects to "V1" for checksum purposes.  (Although that would likely mean re-checksumming all of the objects involved with sha1 again, so really we'd need to require users to `git clone --version=1` or so).

**Comment by cgwalters** [comment]
Hah, and http://thread.gmane.org/gmane.comp.version-control.git/26106/focus=26112

**Comment by fweimer** [comment]
You mentioned https://github.com/git/git/commit/d98b46f, and I'm now confused. The Git hashing code makes up the object types and sizes and prepends them while hashing. This suggests to me that they are *not* part of the actual object data, and you explicitly need to include them if you want them to be present.

The tree structure of Git data provides *some* protection, but my impression is that you want to make your signature independent of the Git hashing (otherwise re-hashing everything does not make sense).

**Comment by cgwalters** [comment]
Some of this confusion may stem from the pseudocode being too high level.  Here's the actual C code:
https://github.com/cgwalters/git-evtag/blob/master/src/git-evtag.c#L105
as well as the Python:
https://github.com/cgwalters/git-evtag/blob/master/src/git-evtag-compute-py#L43

We do explicitly checksum the header.  I'll change the pseudocode to make this more obvious.

**Comment by cgwalters** [comment]
The primary threat `git-evtag` is trying to guard against is the scenario where 5-10 (or however many) years from now, a second preimage attack against SHA1 is found.

As [README.md](README.md) says, that would allow anyone with the ability to change new `git clone` for clients (either at rest, or on the wire) to attack *all* GPG signed git tags that point to the object.

In that scenario, if the relevant object is covered by `git-evtag`, the replaced object will be detected, because we hash the full object content again together with the rest of the commit in SHA512.  (We won't be able to say *which* object is corrupted, so the only recourse then would be to contact others and try to find a pristine repository)

**Comment by cgwalters** [comment]
Based on the current state of discussion, I believe this tool achieves the above primary goal - guard against any future weakness in SHA1 with respect to second preimages for individual objects.

**Comment by cgwalters** [comment]
I very much appreciate the review of course!  If there is something wrong in my responses above, please do reopen!

**Comment by fweimer** [comment]
Agreed, except for the missing trailing `'\0'` in the header, this looks reasonable.
